project:
  type: website
  output-dir: docs       # Damit GitHub Pages den richtigen Ordner findet
  render:
    - "*.qmd"
    - "!test_qmds/"

filters:
  - shinylive
 

website:
  title: "<b>METHODS IN DATA ANALYSIS</b><br>Introduction lecture"
  site-url: "https://dataanalysiscourse.netlify.app/1_datentypen.html"
  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - text: "WELCOME"
        href: index.qmd
      - section: "COURSE-CONTENTS"
        contents:
          - href: 0_markdown.qmd
            text: "Getting started"
          - href: 1_datentypen.qmd
            text: "WEEK 1: Datatypes"
          
  navbar:
    background: "#ffffff"
    right:
      - text: "PYTHON"
        href: "#"
      - text: "R"
        href: "#"

format:
  html:
    self-contained-math: true
    theme: 
      - cosmo
      - custom.scss
    embed-resources: false
    include-in-header: 
      - language-switch.html
      - coi-header.html
      
      # - supabase-auth.html  # Nur aktiv lassen, wenn die Datei wirklich existiert!

execute:
  enabled: true
  freeze: auto
  cache: false
  