project:
  type: website
  output-dir: docs
  resources:
    - "WEEK1/*.md"
    - "WEEK1/*.pdf"
  render:
    - "*.qmd"
    - "!test_qmds/"
    - "!**/*.md"

filters:
  - shinylive

website:
  title: "METHODS IN DATA ANALYSIS"
  site-url: "https://lisaduttenhoefer.github.io/data-analysis-course"
  
  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - text: "WELCOME"
        href: index.qmd
      - section: "COURSE-CONTENTS"
        contents:
          - text: "Getting started"
            href: 0_markdown.qmd
          - section: "WEEK 1: Datatypes"
            contents:
              - text: "Content"
                href: 1_datentypen.qmd
              - text: "Exercises – Week 1"
                href: exercises/week1_exercises.qmd
          - section: "WEEK 2: Data Cleanup"
            contents:
              - text: "Content"
                href: 2_data_cleanup.qmd
              - text: "Exercises – Week 2"
                href: exercises/week2_exercises.qmd

  navbar:
    background: "#ffffff"
    right:
      - text: "PYTHON"
        href: "#"
      - text: "R"
        href: "#"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    embed-resources: false
    include-in-header:
      - language-switch.html
      - coi-header.html
    cache-bust: true

execute:
  enabled: true
  freeze: auto
  cache: false