project:
  type: website
  render:
    - "*.qmd"
    - "!test_qmds/"  # Das Ausrufezeichen schließt den Ordner aus

filters:
  - shinylive

engine: knitr # Oder jupyter, falls du nur Python nutzt. knitr kann beides.

website:
  # Titel mit HTML für Fettdruck und Umbruch
  title: "<b>METHODS IN DATA ANALYSIS</b><br>Introduction lecture"
  
  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - text: "WELCOME"
        href: index.qmd
      - section: "COURSE-CONTENTS"
        contents:
          - href: 0_markdown.qmd
            text: "Getting started"
          - href: 1_datentypen.qmd
            text: "WEEK 1: Datatypes"

          
  navbar:
    background: "#ffffff"
    right:
      - text: "PYTHON"
        href: "#"
      - text: "R"
        href: "#"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    include-in-header: language-switch.html


execute:
  enabled: false
  freeze: auto  # 'auto' bedeutet: Nur re-render, wenn sich die .qmd geändert hat
  cache: true