---
title: "Basic_Data_Structure_in_R"
author: "Dr. Maïwen Caudron-Herger, Prof. Dr. Carl Herrmann"
date: "2023-09-27"
---

::: {.lang-r}

## R and R Markdown

R is a powerful programming language for the analysis of data. It is recommended that you take the introductory classes for R in **DataCamp** to get to know this language before you start coding here. In this course you will learn to use RStudio, a software that allows you to use R in a very user-friendly way.

This is a R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com> or <https://www.markdownguide.org/basic-syntax/>.

When you click the **Knit** button, a document will be generated that includes both content as well as the output of any embedded R code chunks within the document.
Try it out now!

### 1 - Where to get help?

> -   R Tutorial for Beginners at [guru99](https://www.guru99.com/r-tutorial.html)
> -   R courses at [Babraham Bioinformatics](https://www.bioinformatics.babraham.ac.uk/training.html#advancedrtidy)
> -   R for [Data Science](https://r4ds.had.co.nz)
> -   R markdown at [RStudio](https://rmarkdown.rstudio.com/lesson-1.html) and in this [cheatsheet](https://www.markdownguide.org/cheat-sheet/)

### 2 - First steps in programming

We will work with RStudio that is composed of 4 main windows/panels.
The **Editor**, the **Console**, the **Environment** and the **Files** window/panel.

#### 2.1 The Console

The **Console** is where you type commands that you want to execute immediately and don't need to save. For example, if you want to import a data set or visualize a matrix you can type the respective commands in. To execute those commands press enter.

> Type 3 + 4 in the Console and press enter. Can you see that this code was executed immediately? Try something else!

#### 2.2 The Source

The **Source** is the panel for long codes that you are working on and that you want to save. To create a new file, go to the left top corner and click on the `New File` icon with a plus on a green circle and select for example `R Markdown`.

In markdown,
Two \*\* are used for **bold**
One \* is used for *Italic*

#### 2.3 First instructions:

R instructions in a markdown file are written in a "chunk", as seen here below.
Chunks can be added using the `+C` icon at the top right corner of this panel/editor.
There is also a keyboard shortcut for it.

```{shinylive-r}
#| standalone: true
#| viewerHeight: 300
library(shiny)
ui <- fluidPage(
  textAreaInput("code", "R Chunk: Print Hello World!", value = "# print 'Hello world!' on the screen.\nprint('Hello world!')", width = '100%', height = '100px'),
  actionButton("run", "Run Code", class = "btn-success"),
  verbatimTextOutput("out")
)
server <- function(input, output) {
  observeEvent(input$run, { output$out <- renderPrint({ eval(parse(text = input$code)) }) })
}
shinyApp(ui, server)
```

In the Markdown file, you can see the results of the command directly below the "r chunk". Importantly, you can name your chunks.
It is useful to provide different names for the chunks to keep your markdown organized.

So, what has been done here?
We used the function `print()` with the instruction of printing a "string", which is a sequence of "characters".

> What happens in the editor if you remove the second parenthesis? Do you see the red cross appearing? You can click on it and read the comment.
> And what happens if you press "enter" while the second parenthesis is missing?

Usually, `""` and `()` appear both at the same time if you are creating your script in the RStudio editor.
This is very useful and avoid errors due to missing brackets etc ...

Instruction are saved the history of the RStudio session (see "History").
Using the **up** and **down** arrows, you can navigate through this history directly in the RStudio Console and recall a previous instruction.

We can load the string "Hello World!" into a so-called variable using an instruction called **assignment**. An assignment does not return anything in the console. It is just done.

```{shinylive-r}
#| standalone: true
#| viewerHeight: 350
library(shiny)
ui <- fluidPage(
  textAreaInput("code", "R Chunk: Assignments", value = "a <- 'Hello world!'\nhello <- 'Hello world!'\nprint(a)\nprint(hello)", width = '100%', height = '120px'),
  actionButton("run", "Run Code", class = "btn-success"),
  verbatimTextOutput("out")
)
server <- function(input, output) {
  observeEvent(input$run, { output$out <- renderPrint({ eval(parse(text = input$code)) }) })
}
shinyApp(ui, server)
```

Note that the two variables (a and hello) are listed in the "Environment" window of RStudio.

Note: variable assignments in R can be done using either the `<-` symbol, or the `=` symbol:

```{shinylive-r}
#| standalone: true
#| viewerHeight: 300
library(shiny)
ui <- fluidPage(
  textAreaInput("code", "R Chunk: Assignments-2", value = "a <- 2\na = 2\nprint(a)", width = '100%', height = '100px'),
  actionButton("run", "Run Code", class = "btn-success"),
  verbatimTextOutput("out")
)
server <- function(input, output) {
  observeEvent(input$run, { output$out <- renderPrint({ eval(parse(text = input$code)) }) })
}
shinyApp(ui, server)
```

**Important!!!**
R is case sensitive. `hello` is a known variable, but `Hello` not!
Typing `Hello` will result in an error message:

```{shinylive-r}
#| standalone: true
#| viewerHeight: 300
library(shiny)
ui <- fluidPage(
  textAreaInput("code", "R Chunk: Case sensitivity", value = "Hello # Error: object 'Hello' not found", width = '100%', height = '80px'),
  actionButton("run", "Run Code", class = "btn-success"),
  verbatimTextOutput("out")
)
server <- function(input, output) {
  observeEvent(input$run, { output$out <- renderPrint({ eval(parse(text = input$code)) }) })
}
shinyApp(ui, server)
```

We can also use R as a calculator to perform mathematical operations, e.g. basic addition and multiplication:

```{shinylive-r}
#| standalone: true
#| viewerHeight: 350
library(shiny)
ui <- fluidPage(
  textAreaInput("code", "R Chunk: Mathematical operations", value = "x <- 5\ny <- 3\nSum <- x+y\nSum*5", width = '100%', height = '120px'),
  actionButton("run", "Run Code", class = "btn-success"),
  verbatimTextOutput("out")
)
server <- function(input, output) {
  observeEvent(input$run, { output$out <- renderPrint({ eval(parse(text = input$code)) }) })
}
shinyApp(ui, server)
```

It is possible to delete a variable by using the function `rm()`. This function needs to be used with a lot of care!!!

```{shinylive-r}
#| standalone: true
#| viewerHeight: 300
library(shiny)
ui <- fluidPage(
  textAreaInput("code", "R Chunk: Removing variables", value = "a <- 10\nrm(a)\n# a is now gone", width = '100%', height = '100px'),
  actionButton("run", "Run Code", class = "btn-success"),
  verbatimTextOutput("out")
)
server <- function(input, output) {
  observeEvent(input$run, { output$out <- renderPrint({ eval(parse(text = input$code)) }) })
}
shinyApp(ui, server)
```

"a" disappeared from the environment also called workspace. hello is still listed.

The function `ls()` can also give you the list of variables or objects in your workspace/environment.

```{shinylive-r}
#| standalone: true
#| viewerHeight: 300
library(shiny)
ui <- fluidPage(
  textAreaInput("code", "R Chunk: Listing variables", value = "ls()", width = '100%', height = '80px'),
  actionButton("run", "Run Code", class = "btn-success"),
  verbatimTextOutput("out")
)
server <- function(input, output) {
  observeEvent(input$run, { output$out <- renderPrint({ eval(parse(text = input$code)) }) })
}
shinyApp(ui, server)
```

... [Der Rest des Inhalts wird analog mit Shinylive-Chunks fortgesetzt] ...

## Wissenstest

::: {.card .p-4 .shadow-sm}
<h5 style="color: #1a4d1a; font-weight: 800;">QUIZ: WOCHE 0 ABSCHLIESSEN</h5>
<p>Klicke hier, um zu bestätigen, dass du die Grundlagen bearbeitet hast.</p>
<button onclick="markTaskDone('woche0')" class="btn btn-primary" style="background-color: #1a4d1a; border: none;">ERLEDIGT</button>
</div>
:::

:::

::: {.lang-python}
## Python Setup (Coming soon)
Dieser Bereich wird für Python-Inhalte reserviert.
:::
```
